### ISSUE TITLE
This repository might serve no useful purpose

### ISSUE THREAD

**Issue by eggyknap** [EndPointCorp/com.endpoint.lg.browser.static#2]
I created the static browser activity, and later realized it was better to incorporate its function into the browser service (https://github.com/EndPointCorp/com.endpoint.lg.browser.service). It was supposed to be a simple service to provide static browser windows, like the LG touchscreen, that always need to be open. The browser service supports static pages now, so we don't need this separate activity. Unless of course someone can come up with a good reason to keep it.

**Comment by mvollrath** [comment]
It gives us a lot more flexibility to keep static pages configured separate from the browser service.

Imagine that you want different static pages for different experiences.  If they are bundled with the service, you need a new service for each experience where you could otherwise use the same one.

Code that is common between browser.static and browser.service should be factored out into the support library.  This may include facilities for launching Chrome with myriad options when the need arises.

Architecturally, the idea is to keep activities as light and single-purpose as possible.  Think micro-services.  e.g. Earth's interfaces are broken out instead of having a single monolithic activity bundling the launcher with many topics with the goal of making it easier to deal with the code and using intentional configuration instead of implicit logic determining features/capabilities.

**Comment by eggyknap** [comment]
Fair enough. I'll say, then, that I have no idea if this service works at all. In fact, I'll create an issue saying "test this".

**Comment by mvollrath** [comment]
Thanks Josh!
